function [methodinfo,structs,enuminfo,ThunkLibName]=ps2000WrapMFile_win32
%PS2000WRAPMFILE_WIN32 Create structures to define interfaces found in 'ps2000Wrap'.

%This function was generated by loadlibrary.m parser version  on Thu Jul 13 16:32:01 2017
%perl options:'ps2000Wrap.i -outfile=ps2000WrapMFile_win32.m'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival);
ThunkLibName=[];
% extern int16_t _stdcall PollFastStreaming ( int16_t handle ); 
fcns.name{fcnNum}='PollFastStreaming'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern void _stdcall SetBuffer ( int16_t handle , int16_t channel , int16_t * buffer , uint32_t bufferSize ); 
fcns.name{fcnNum}='SetBuffer'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16', 'int16', 'int16Ptr', 'uint32'};fcnNum=fcnNum+1;
% extern void _stdcall SetAggregateBuffer ( int16_t handle , int16_t channel , int16_t * bufferMax , int16_t * bufferMin , uint32_t bufferSize ); 
fcns.name{fcnNum}='SetAggregateBuffer'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16', 'int16', 'int16Ptr', 'int16Ptr', 'uint32'};fcnNum=fcnNum+1;
% extern int16_t _stdcall FastStreamingReady ( int16_t handle ); 
fcns.name{fcnNum}='FastStreamingReady'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern uint32_t _stdcall GetFastStreamingDetails ( int16_t handle , int16_t * overflow , uint32_t * triggeredAt , int16_t * triggered , int16_t * auto_stop , int16_t * appBufferFull , uint32_t * startIndex ); 
fcns.name{fcnNum}='GetFastStreamingDetails'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'int16', 'int16Ptr', 'uint32Ptr', 'int16Ptr', 'int16Ptr', 'int16Ptr', 'uint32Ptr'};fcnNum=fcnNum+1;
% extern void _stdcall setEnabledChannels ( int16_t handle , int16_t * enabledChannels ); 
fcns.name{fcnNum}='setEnabledChannels'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16', 'int16Ptr'};fcnNum=fcnNum+1;
% extern void _stdcall clearFastStreamingParameters ( int16_t handle ); 
fcns.name{fcnNum}='clearFastStreamingParameters'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int16'};fcnNum=fcnNum+1;
% extern int16_t _stdcall setCollectionInfo ( int16_t handle , uint32_t collectionSize , uint32_t overviewBufferSize ); 
fcns.name{fcnNum}='setCollectionInfo'; fcns.calltype{fcnNum}='stdcall'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int16', 'uint32', 'uint32'};fcnNum=fcnNum+1;
structs.WRAP_BUFFER_INFO.members=struct('appBuffers', 'int16PtrPtr', 'bufferSizes', 'uint32#4');
methodinfo=fcns;